In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [6]:
x = tf.Variable(4.0)
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=4.0>

In [7]:
#gradienttape records all operations that occur in our forward pass
with tf.GradientTape() as tape:
    y=x**2

In [8]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=16.0>

In [9]:
#instance of the gradient tape that we had set up has recorded our forward pass
# tape.gradient cal gradient of y wrt x

dx_dy = tape.gradient(y,x)
dx_dy

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [11]:
w = tf.Variable(tf.random.normal((4,2)))
w

<tf.Variable 'Variable:0' shape=(4, 2) dtype=float32, numpy=
array([[ 0.13409656, -0.3902156 ],
       [-0.3993676 ,  1.5321133 ],
       [-1.3828703 , -0.7061677 ],
       [-0.6292585 ,  0.3086846 ]], dtype=float32)>

In [13]:
b = tf.Variable(tf.ones(2,dtype=tf.float32))
b

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [14]:
x = tf.Variable([[1.1,2.1,4.2,60.]],dtype=tf.float32)
x

<tf.Variable 'Variable:0' shape=(1, 4) dtype=float32, numpy=array([[ 1.1,  2.1,  4.2, 60. ]], dtype=float32)>

In [ ]:
#inorder to be able to invoke tape.gradient multiple times we set persistent = true


In [15]:
#y=wx+b is explaination of y= tf.matmul(x,w)+b
# tf.reduce_mean cal mse
with tf.GradientTape(persistent=True) as tape:
    y= tf.matmul(x,w)+b
    loss = tf.reduce_mean(y**2)
    

In [16]:
#cal gradient of loss wrt w and b
[dl_dw,dl_db] = tape.gradient(loss,[w,b])

In [17]:
dl_db

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-43.254734,  19.343372], dtype=float32)>

In [18]:
dl_dw

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[  -47.580208,    21.27771 ],
       [  -90.83494 ,    40.62108 ],
       [ -181.66988 ,    81.24216 ],
       [-2595.284   ,  1160.6023  ]], dtype=float32)>