In [23]:
#tensors are multi dimensoional arrays like numpy
#tensors are immutable
import tensorflow as tf
import numpy as np

#Below line prints where our tensors are located and on which device these are getting executed
tf.debugging.set_log_device_placement(True)

In [24]:

tf.executing_eagerly()


True

In [25]:
#tensor can hold a scalar constant ie a value t0
x0 = tf.constant(3)
x0


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [26]:
x0.dtype

tf.int32

In [27]:
#can perform arithemtic operation on tensor as well
res0 = x0+5
res0

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [28]:
#1 d array or a vector
x1 = tf.constant([1,1.2,5.1,9.0])
x1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1. , 1.2, 5.1, 9. ], dtype=float32)>

In [29]:
#broadcasting arithemetic operartions
res1 = x1 + 5
res1

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 6. ,  6.2, 10.1, 14. ], dtype=float32)>

In [30]:
#adding two tensors via tf.add()
res2 = tf.add(x1,tf.constant(5.0))
res2

Executing op Add in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 6. ,  6.2, 10.1, 14. ], dtype=float32)>

In [31]:
res2 = x1+tf.constant(5.0)
res2

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 6. ,  6.2, 10.1, 14. ], dtype=float32)>

In [32]:
#2d
x2 = tf.constant([[1.1,2.1],[2,1]])
x2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.1, 2.1],
       [2. , 1. ]], dtype=float32)>

In [33]:
#changing the datatype of a tensor is done by tf.cast()
x2 = tf.cast(x2,tf.float32)
x2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.1, 2.1],
       [2. , 1. ]], dtype=float32)>

In [35]:
x2 = tf.cast(x2,tf.float32)
x2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.1, 2.1],
       [2. , 1. ]], dtype=float32)>

In [36]:
x3 = tf.constant([[1,1,2],[1.1,2.4,4.1]])
x4 = tf.constant([[1.5,1.1,2],[1.2,4.4,1.1]])
 
# performing tensor multiplication

res3 = tf.multiply(x3,x4)
res3

Executing op Mul in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.5 ,  1.1 ,  4.  ],
       [ 1.32, 10.56,  4.51]], dtype=float32)>

In [37]:
#tensor converted to a numpy arrar
arr_x1 = x1.numpy()
arr_x1

array([1. , 1.2, 5.1, 9. ], dtype=float32)

In [38]:
#numpy to tensor
arr_x2 = np.array([1,1,12,5])
x5 = tf.convert_to_tensor(arr_x2)
x5

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  1, 12,  5])>

In [39]:
#we can perform numpy operation on a tensor aswell
np.square(x5)


array([  1,   1, 144,  25], dtype=int32)

In [40]:
#to check if a variabe holds a tensor or not 
tf.is_tensor(arr_x2)

False

In [42]:
# helper methods to initialize tensor with specific value
t0 = tf.zeros([3,5],tf.int32)
t0

Executing op Fill in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

In [43]:
t1 = tf.ones([2,2],tf.int32)
t1


Executing op Fill in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]])>

In [47]:
#reshaping a tensor
t1 = tf.reshape(t1,[4,1])
t1

Executing op Reshape in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [1],
       [1],
       [1]])>

In [49]:
#Variables 


#variables hold tensors and are mutable in nature

v1 = tf.Variable([[1.2,12.2,1],[2,5,5]])
v1

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 1.2, 12.2,  1. ],
       [ 2. ,  5. ,  5. ]], dtype=float32)>

In [51]:
v2 = tf.Variable([[1,2,3],[2,5,6]], dtype=tf.float32)
v2

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [2., 5., 6.]], dtype=float32)>

In [ ]:
tf.add(v1,v2)


In [53]:
tf.convert_to_tensor(v1)


Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.2, 12.2,  1. ],
       [ 2. ,  5. ,  5. ]], dtype=float32)>

In [54]:
#to see how variable is mutable
#we perform operation on a variable using assign() which will assign lelements or values to the tensor

v1.assign([[1.2,7,1],[3,5,8]])
v1

Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1.2, 7. , 1. ],
       [3. , 5. , 8. ]], dtype=float32)>

In [56]:
#assigning an element at specific place in a variable
v1[0,1].assign(100)
v1

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ResourceStridedSliceAssign in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.2, 100. ,   1. ],
       [  3. ,   5. ,   8. ]], dtype=float32)>

In [58]:
v1.assign_add([[0.2,0.5,2.],[3,0.7,0.9]])
v1

Executing op AssignAddVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.6000001, 101.       ,   5.       ],
       [  9.       ,   6.3999996,   9.799999 ]], dtype=float32)>

In [59]:
v1.assign_sub([[0.2,0.5,2.],[3,0.7,0.9]])
v1

Executing op AssignSubVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.4000001, 100.5      ,   3.       ],
       [  6.       ,   5.7      ,   8.9      ]], dtype=float32)>

In [60]:
var_b = tf.Variable(v1)
var_b

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.4000001, 100.5      ,   3.       ],
       [  6.       ,   5.7      ,   8.9      ]], dtype=float32)>

In [61]:
#mutating the var_b with new val using assign()
var_b.assign([[199,3,1220],[112,514,111]])
var_b

Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 199.,    3., 1220.],
       [ 112.,  514.,  111.]], dtype=float32)>

In [62]:
print(var_b.numpy())
print(v1.numpy())

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0
[[ 199.    3. 1220.]
 [ 112.  514.  111.]]
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0
[[  1.4000001 100.5         3.       ]
 [  6.          5.7         8.9      ]]


In [ ]:
#variables do not share memory

In [ ]:
#executing_eagerly means our program exection is done right away and we dont have to create a session for it which is used 
# to execute static computational graph in tf1
