In [1]:
import tensorflow as tf

In [18]:
rank_3 = tf.Variable([[["tf"],["12"]],[["ya"],["12"]]])


In [19]:
tf.rank(rank_3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [20]:
rank_3

<tf.Variable 'Variable:0' shape=(2, 2, 1) dtype=string, numpy=
array([[[b'tf'],
        [b'12']],

       [[b'ya'],
        [b'12']]], dtype=object)>

In [21]:
rank_3.shape

TensorShape([2, 2, 1])

In [25]:
rank_1 = tf.Variable(["1","2","3","4","5"])

In [26]:
tf.rank(rank_1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [27]:
rank_1.shape

TensorShape([5])

In [28]:
rank2 = tf.Variable([['wewrr'],['wew'],['adad'],['ada'],["da"]])

In [29]:
tf.rank(rank2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [30]:
rank2.shape

TensorShape([5, 1])

In [32]:
rank3 = tf.Variable([[["werew"]],[["vsc"]],[["adada"]],[["dads"]],[["vff"]]])

In [33]:
tf.rank(rank3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [35]:
rank3.shape

TensorShape([5, 1, 1])

In [38]:
altrank_3 = tf.Variable([["1"]]) #list inside a list is rank 2

In [39]:
tf.rank(altrank_3)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [40]:
t = tf.Variable([[["r"]]]) #list inside nested list is rank 3
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [47]:
f = tf.Variable([[[["rr","jjj","jgvhg"],["sas","hhh","bjhgh"]]]])
tf.rank(f)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [48]:
f.shape  

TensorShape([1, 1, 2, 3])

In [50]:
g = tf.Variable([[["aaassa","Adada","ada","ada"],["asdad","adada","wew","wewe"]]])

In [51]:
g.shape #1 = outermost list, 2 = number of list inside the outermost list, 4 = number of element inside those list

TensorShape([1, 2, 4])

In [52]:
v = tf.Variable([[["aaassa","Adada","ada","ada"],["asdad","adada","wew","wewe"],["dadad","adadada","bdvvd","vd"]]])
v.shape

TensorShape([1, 3, 4])

In [54]:
v.eval

<bound method BaseResourceVariable.eval of <tf.Variable 'Variable:0' shape=(1, 3, 4) dtype=string, numpy=
array([[[b'aaassa', b'Adada', b'ada', b'ada'],
        [b'asdad', b'adada', b'wew', b'wewe'],
        [b'dadad', b'adadada', b'bdvvd', b'vd']]], dtype=object)>>

In [55]:
v.dtype

tf.string

In [69]:
k = tf.Variable([["acc","aacc"],["acc","dacc"],["asa","asd"],["asa","asa"]])
tf.rank(k)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [70]:
k.shape

TensorShape([4, 2])

In [71]:
b = tf.Variable([[["ddvd","vdvvv"],["AHAH","aCAC"]],[["Sdvdd","rrg"],["ASA","CCC"]],[["Ssfsf","ffssd"],["aSA","AAAS"]],[["Sdsf","fsfs"],["ASAX","ASDAD"]]])
tf.rank(b)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [72]:
b.shape

TensorShape([4, 2, 2])

In [73]:
m = tf.Variable([[["ddvd","vdvvv"]],[["Sdvdd","rrg"]],[["Ssfsf","ffssd"]],[["Sdsf","fsfs"]]])
tf.rank(m)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [74]:
m.shape # 4 = number of list inside outer most list, 1 = number of list inside of the that list, 2 = number of elements inside list

TensorShape([4, 1, 2])

In [76]:
n = tf.Variable([[["ada","daad"],["ada","adad"],["adad","ada"],["tt","Asad"]]])
n.shape

TensorShape([1, 4, 2])

In [82]:
x = tf.Variable([["asda","ass","asas"],["aa","Assa","aaa"],["ada","asa","www"],["sa","ada","ads"]])
tf.rank(x)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [83]:
x.shape

TensorShape([4, 3])

# w = tf.Variable([[["asa","asa"],["asa","asa"]]])
w.shape

In [100]:
tensor1 = tf.reshape(x,[4,-1]) #-1 tells the tensor to cal the number of element when the size of list is 4
                               #so as we can see, we have 4 list , which has 3 elements each in it. 4x3 = 12
tensor1

<tf.Tensor: shape=(4, 3), dtype=string, numpy=
array([[b'asda', b'ass', b'asas'],
       [b'aa', b'Assa', b'aaa'],
       [b'ada', b'asa', b'www'],
       [b'sa', b'ada', b'ads']], dtype=object)>

In [103]:
tensor2 = tf.reshape(x,[3,2,2])
tensor2

<tf.Tensor: shape=(3, 2, 2), dtype=string, numpy=
array([[[b'asda', b'ass'],
        [b'asas', b'aa']],

       [[b'Assa', b'aaa'],
        [b'ada', b'asa']],

       [[b'www', b'sa'],
        [b'ada', b'ads']]], dtype=object)>

In [104]:
tensor3 = tf.reshape(x,[3,2,-1])
tensor3

<tf.Tensor: shape=(3, 2, 2), dtype=string, numpy=
array([[[b'asda', b'ass'],
        [b'asas', b'aa']],

       [[b'Assa', b'aaa'],
        [b'ada', b'asa']],

       [[b'www', b'sa'],
        [b'ada', b'ads']]], dtype=object)>

In [116]:
c = tf.ones([3,3,3])
c

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [117]:
t = tf.reshape(c,[27])
t

<tf.Tensor: shape=(27,), dtype=float32, numpy=
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>